DELETE FROM Usuarios;
DELETE FROM Produccion;
DELETE FROM Almacenamiento;
DELETE FROM Cultivos;
DELETE FROM Trabajadores;

ALTER TABLE Usuarios AUTO_INCREMENT = 1;
ALTER TABLE Almacenamiento AUTO_INCREMENT = 1;
ALTER TABLE Cultivos AUTO_INCREMENT = 1;
ALTER TABLE Produccion AUTO_INCREMENT = 1;